// usage:  protoc --go_out=plugins=grpc:. proto/*.proto

//指定proto版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/opencv.proto

//指定包名

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//Request 请求结构
type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpcImg   string `protobuf:"bytes,1,opt,name=cpc_img,json=cpcImg,proto3" json:"cpc_img,omitempty"`
	SmallImg string `protobuf:"bytes,2,opt,name=small_img,json=smallImg,proto3" json:"small_img,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_opencv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opencv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_opencv_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetCpcImg() string {
	if x != nil {
		return x.CpcImg
	}
	return ""
}

func (x *Request) GetSmallImg() string {
	if x != nil {
		return x.SmallImg
	}
	return ""
}

//Response 响应结构
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Distance int64 `protobuf:"varint,1,opt,name=distance,proto3" json:"distance,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_opencv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_opencv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_opencv_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetDistance() int64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

var File_proto_opencv_proto protoreflect.FileDescriptor

var file_proto_opencv_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x76, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x70, 0x63, 0x5f, 0x69, 0x6d,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x70, 0x63, 0x49, 0x6d, 0x67, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x6d, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x49, 0x6d, 0x67, 0x22, 0x26, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x32, 0x38, 0x0a, 0x06, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x56, 0x12, 0x2e,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_opencv_proto_rawDescOnce sync.Once
	file_proto_opencv_proto_rawDescData = file_proto_opencv_proto_rawDesc
)

func file_proto_opencv_proto_rawDescGZIP() []byte {
	file_proto_opencv_proto_rawDescOnce.Do(func() {
		file_proto_opencv_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_opencv_proto_rawDescData)
	})
	return file_proto_opencv_proto_rawDescData
}

var file_proto_opencv_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_opencv_proto_goTypes = []interface{}{
	(*Request)(nil),  // 0: proto.Request
	(*Response)(nil), // 1: proto.Response
}
var file_proto_opencv_proto_depIdxs = []int32{
	0, // 0: proto.OpenCV.GetDistance:input_type -> proto.Request
	1, // 1: proto.OpenCV.GetDistance:output_type -> proto.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_opencv_proto_init() }
func file_proto_opencv_proto_init() {
	if File_proto_opencv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_opencv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_opencv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_opencv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_opencv_proto_goTypes,
		DependencyIndexes: file_proto_opencv_proto_depIdxs,
		MessageInfos:      file_proto_opencv_proto_msgTypes,
	}.Build()
	File_proto_opencv_proto = out.File
	file_proto_opencv_proto_rawDesc = nil
	file_proto_opencv_proto_goTypes = nil
	file_proto_opencv_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OpenCVClient is the client API for OpenCV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OpenCVClient interface {
	//定义方法
	GetDistance(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type openCVClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenCVClient(cc grpc.ClientConnInterface) OpenCVClient {
	return &openCVClient{cc}
}

func (c *openCVClient) GetDistance(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.OpenCV/GetDistance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpenCVServer is the server API for OpenCV service.
type OpenCVServer interface {
	//定义方法
	GetDistance(context.Context, *Request) (*Response, error)
}

// UnimplementedOpenCVServer can be embedded to have forward compatible implementations.
type UnimplementedOpenCVServer struct {
}

func (*UnimplementedOpenCVServer) GetDistance(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDistance not implemented")
}

func RegisterOpenCVServer(s *grpc.Server, srv OpenCVServer) {
	s.RegisterService(&_OpenCV_serviceDesc, srv)
}

func _OpenCV_GetDistance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenCVServer).GetDistance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OpenCV/GetDistance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenCVServer).GetDistance(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _OpenCV_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.OpenCV",
	HandlerType: (*OpenCVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDistance",
			Handler:    _OpenCV_GetDistance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/opencv.proto",
}
